spring:
  application:
    name: technical_test_backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: buana

server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.buana.technical_test_backend: INFO
  file:
    name:

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /